/* --------------------------------------------------------------------
   Code generated by a SAS task
   
   Generated on Thursday, August 22, 2013 at 4:56:22 PM
   By task:     Import Data Wizard
   
   Source file: C:\Users\Bright\Documents\NCSU\Fall\Logistic
   Regression\HW 1\fludata.xlsx
   Server:      Local File System
   
   Output data: WORK.fludata
   Server:      Local
   -------------------------------------------------------------------- */

/* --------------------------------------------------------------------
   This DATA step reads the data values from a temporary text file
   created by the Import Data wizard. The values within the temporary
   text file were extracted from the Excel source file.
   -------------------------------------------------------------------- */

DATA logistic.fludata;
    LENGTH
        Flu              $ 3
        Age                8
        Distance           8
        Gender           $ 6
        Income           $ 6
        Previous         $ 3
        Race             $ 15
        Visits             8 ;
    FORMAT
        Flu              $CHAR3.
        Age              BEST12.
        Distance         BEST12.
        Gender           $CHAR6.
        Income           $CHAR6.
        Previous         $CHAR3.
        Race             $CHAR15.
        Visits           BEST12. ;
    INFORMAT
        Flu              $CHAR3.
        Age              BEST12.
        Distance         BEST12.
        Gender           $CHAR6.
        Income           $CHAR6.
        Previous         $CHAR3.
        Race             $CHAR15.
        Visits           BEST12. ;
    INFILE 'C:\Users\Bright\AppData\Local\Temp\SEG6780\fludata-0cd76867e5734b2982c834baf6772bd7.txt'
        LRECL=45
        ENCODING="WLATIN1"
        TERMSTR=CRLF
        DLM='7F'x
        MISSOVER
        DSD ;
    INPUT
        Flu              : $CHAR3.
        Age              : BEST32.
        Distance         : BEST32.
        Gender           : $CHAR6.
        Income           : $CHAR6.
        Previous         : $CHAR3.
        Race             : $CHAR15.
        Visits           : BEST32. ;
RUN;
